### ISSUE TITLE
Code 

### ISSUE THREAD

**Issue by sinAshish** [saltoricristiano/SF-UDA-3DV#1]
Hi,

Your work is truly amazing!

When do you plan on releasing the code?

**Comment by saltoricristiano** [comment]
Hi @sinAshish , 

thank you for the interest in our work!
As soon as we will solve bureaucratic issues, we will upload the code!

**Comment by Hyeokreal** [comment]
Hi,

Thank you for your amazing works!
I'm really looking forward it too.

**Comment by jhzhang19** [comment]
Hi,thank you for your great works!
When do you plan to release the code? I an really looking forward it.

**Comment by saltoricristiano** [comment]
Hi @jhzhang19 and @Hyeokreal, 

thanks for your interest in our work!
We are still facing some bureaucratic issues for releasing the code.
Once solved we will release the code!

**Comment by vehxianfish** [comment]
Hi, When do you plan on releasing the code?
